# Use root/example as user/password credentials

services:

  db:
    container_name: mariadb-12.0.1-ubi9-rc
    image: mariadb:12.0.1-ubi9-rc
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
    - 3308:3306
  adminer:
    container_name: adminer-latest
    image: adminer:latest
    restart: always
    ports:
      - 9080:8080
